[engine]
browserHswThreadCount = 25
browserCount = 6
rotation = 20
rotation_wait = 10

[browser]
name = "dolphin"
useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
os = "win"
headless = false

[mock]
enable_hsj = false
inject_hsw = false
inject_spoof = false
block_register = true
hsw_version = "28ff887"

[server]
port = 1234

[debug]
gotos = [
    "https://www.browserscan.net/",
    "https://browserleaks.com/webgl",
    "https://browserleaks.com/webrtc",
    "https://browserleaks.com/canvas",
    "https://browserleaks.com/webgl",
    "https://browserleaks.com/tls",
    "https://browserleaks.com/javascript",
    "https://browserleaks.com/fonts",
    "https://browserleaks.com/ip",
    "https://bot.sannysoft.com/",
    "https://abrahamjuliot.github.io/creepjs/",
]
