[engine]
browserHswThreadCount = 10
browserCount = 6
hidenium = false
gologin = true
rotation = 30
rotation_wait = 10

[mock]
hsw = false
spoofing = true
version = "6f48ffb"

[server]
port = 1234