[engine]
browserHswThreadCount = 30
browserCount = 4
rotation = 30000
rotation_wait = 10

[browser]
name = "gologin"
useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
os = "win"
headless = false

[mock]
inject_hsw = false
inject_spoof = false
block_register = true
hsw_version = "31892fb"

[server]
port = 1234

[debug]
gotos = [
	"https://www.browserscan.net/",
	"https://browserleaks.com/webgl",
	"https://browserleaks.com/webrtc",
	"https://browserleaks.com/canvas",
	"https://browserleaks.com/webgl",
	"https://browserleaks.com/tls",
	"https://browserleaks.com/javascript",
	"https://browserleaks.com/fonts",
	"https://browserleaks.com/ip",
	"https://bot.sannysoft.com/",
	"https://abrahamjuliot.github.io/creepjs/",
]
